### ISSUE TITLE
Example `http-client` fails to build

### ISSUE THREAD

**Issue by tomfitzhenry** [esp-rs/no_std-training#21]
I've tried following https://esp-rs.github.io/no_std-training/ but had troubles compiling the `http-client` example.

Steps to reproduce (running on NixOS):

```
$ rustup toolchain install nightly-2023-06-25 --component rust-src --target riscv32imc-unknown-none-elf
$ rustup --version
rustup 1.26.0 (1980-01-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.72.0-nightly (f7ca9df69 2023-06-24)`
$ git clone https://github.com/esp-rs/no_std-training
$ cd no_std-training/intro/http-client/
$ cargo run --release --example http-client
```

I have attached the build output: [http-client.txt](https://github.com/esp-rs/no_std-training/files/13235318/http-client.txt).

I'm not very familiar with Rust, but it looks like dependencies `embedded-io` and `linked_list_allocator` failed to build.

I was able to build the hello world, per https://esp-rs.github.io/no_std-training/02_4_hello_world.html .

**Comment by SergioGasquez** [comment]
Just tried reproducing your issue, and I was able to build it successfully, do you mind trying to do `cargo clean` on the `http-client` ?

**Comment by SergioGasquez** [comment]
Oh right, installing Rust via package managers tend to be problematic: https://esp-rs.github.io/book/installation/rust.html

Glad that is now working!
