### ISSUE TITLE
No link to crate documentation in intro/http-client/src/main.rs 

### ISSUE THREAD

**Issue by tommythorn** [esp-rs/no_std-training#9]
Context: I have a reasonable Rust experience, but zero experience with ESP32. I got the ESP32-C3-RUST dev board and followed the https://esp-rs.github.io/no_std-training/ up until the http client example.

The example requires you to configure the clocks, but that's a bit of an abrupt departure.  There's no link to the documentation for this. 

Only when using Visual Code Studio can I find the hal crate, but it doesn't really make it clear how to proceed from here.  By grepping around deep inside .cargo I finally find examples-util/src/lib.rs that suggests I should use `ClockControl::configure(system.clock_control, CpuClock::Clock160MHz).freeze();` but I'm at a loss at how I was supposed to have known that.

I imagine I'm not the only to be confused at this point.

ADD: this is apparently only the beginning of the trouble.  Hopefully there is documentation that I'm just missing.

**Comment by playfulFence** [comment]
Thanks, @tommythorn,  real user feedback helps us to have a better idea how to make our examples even more understandable and useful!

Just in case, recently we've updated [docs](https://docs.rs/esp32c3-hal/latest/esp32c3_hal/index.html) for all of our modules for each chip where Rust is supported, so please feel free to give some feedback there as well!
